//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace Dormulaire_DB.Web
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class InscriptionEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new InscriptionEntities object using the connection string found in the 'InscriptionEntities' section of the application configuration file.
        /// </summary>
        public InscriptionEntities() : base("name=InscriptionEntities", "InscriptionEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new InscriptionEntities object.
        /// </summary>
        public InscriptionEntities(string connectionString) : base(connectionString, "InscriptionEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new InscriptionEntities object.
        /// </summary>
        public InscriptionEntities(EntityConnection connection) : base(connection, "InscriptionEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Utilisateur> Utilisateur
        {
            get
            {
                if ((_Utilisateur == null))
                {
                    _Utilisateur = base.CreateObjectSet<Utilisateur>("Utilisateur");
                }
                return _Utilisateur;
            }
        }
        private ObjectSet<Utilisateur> _Utilisateur;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Utilisateur EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUtilisateur(Utilisateur utilisateur)
        {
            base.AddObject("Utilisateur", utilisateur);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InscriptionModel", Name="Utilisateur")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Utilisateur : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Utilisateur object.
        /// </summary>
        /// <param name="nom">Initial value of the nom property.</param>
        /// <param name="prenom">Initial value of the prenom property.</param>
        /// <param name="peuso">Initial value of the peuso property.</param>
        public static Utilisateur CreateUtilisateur(global::System.String nom, global::System.String prenom, global::System.String peuso)
        {
            Utilisateur utilisateur = new Utilisateur();
            utilisateur.nom = nom;
            utilisateur.prenom = prenom;
            utilisateur.peuso = peuso;
            return utilisateur;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nom
        {
            get
            {
                return _nom;
            }
            set
            {
                if (_nom != value)
                {
                    OnnomChanging(value);
                    ReportPropertyChanging("nom");
                    _nom = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("nom");
                    OnnomChanged();
                }
            }
        }
        private global::System.String _nom;
        partial void OnnomChanging(global::System.String value);
        partial void OnnomChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String prenom
        {
            get
            {
                return _prenom;
            }
            set
            {
                OnprenomChanging(value);
                ReportPropertyChanging("prenom");
                _prenom = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("prenom");
                OnprenomChanged();
            }
        }
        private global::System.String _prenom;
        partial void OnprenomChanging(global::System.String value);
        partial void OnprenomChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String peuso
        {
            get
            {
                return _peuso;
            }
            set
            {
                OnpeusoChanging(value);
                ReportPropertyChanging("peuso");
                _peuso = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("peuso");
                OnpeusoChanged();
            }
        }
        private global::System.String _peuso;
        partial void OnpeusoChanging(global::System.String value);
        partial void OnpeusoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] avatar
        {
            get
            {
                return StructuralObject.GetValidValue(_avatar);
            }
            set
            {
                OnavatarChanging(value);
                ReportPropertyChanging("avatar");
                _avatar = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("avatar");
                OnavatarChanged();
            }
        }
        private global::System.Byte[] _avatar;
        partial void OnavatarChanging(global::System.Byte[] value);
        partial void OnavatarChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                OnemailChanging(value);
                ReportPropertyChanging("email");
                _email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("email");
                OnemailChanged();
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> age
        {
            get
            {
                return _age;
            }
            set
            {
                OnageChanging(value);
                ReportPropertyChanging("age");
                _age = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("age");
                OnageChanged();
            }
        }
        private Nullable<global::System.DateTime> _age;
        partial void OnageChanging(Nullable<global::System.DateTime> value);
        partial void OnageChanged();

        #endregion
    
    }

    #endregion
    
}
